baseURL = 'https://highpingblorg.com/'
languageCode = 'en-us'
title = 'highpingblorg'
author = 'Omer Mokhamed Makhmud'
theme = 'risotto'

[params.about]
title = 'highpingblorg'
description = 'totally a professional blog'
logo_image = 'images/logo.png'
