baseURL = 'https://highpingblorg.com/'
languageCode = 'en-us'
title = 'highpingblorg'
theme = 'risotto'
author = 'Omer "highpingblorg" Mokhamed Makhmud'
paginate = 3
DefaultContentLanguage = 'en-us'
enableInlineShortCodes = true
ignoreErrors = ['error-remote-getjson']


sectionPagesMenu = 'main'

[params]
noindex = false
customCSS = "css/custom.css"

[params.theme]
palette = 'base16-dark'

[params.about]
title = ' highpingblorg'
description = 'The blog of __Omer Mokhamed Makhmud__. A Cybersecurity and Open-source enthusiast.'
logo_image = 'images/pfp.jpeg'

[[params.socialLinks]]
icon = 'fa-brands fa-github'
title = 'github'
url = 'https://github.com/highpingblorg'

[[params.socialLinks]]
icon = 'fa-brands fa-linkedin'
title = 'LinkedIn'
url = 'https://www.linkedin.com/in/omermm/'
